export { default as Home } from './home/container/Home'
export { default as Cart } from './cart/container/Cart'
export { default as Categories } from './categories/container/Categories'
export { default as Profile } from './Profile/container/Profile'
export { default as SingleCategorie } from './singleCategorie/container/SingleCategorie'
export { default as SearchPage } from './search/container/SearchPage'
export { default as Checkout } from './checkout/container/Checkout'
export { default as ProfileInfo } from './Profile/container/ProfileInfo'
export { default as MyOrders } from './Profile/container/MyOrders'
export { default as Address } from './Profile/container/Address'
export { default as Map } from './Profile/container/Map'

